Gemfile:
  optional:
    ':development':
       - gem: 'puppet-strings'
       - gem: 'puppet-lint-file_ensure-check'
       - gem: 'puppet-lint-reference_on_declaration_outside_of_class-check'
       - gem: 'puppet-lint-unquoted_string-check'
       - gem: 'puppet-lint-trailing_comma-check'
       - gem: 'puppet-lint-resource_reference_syntax'
       - gem: 'puppet-lint-classes_and_types_beginning_with_digits-check'
       - gem: 'puppet-lint-global_resource-check'
       - gem: 'puppet-lint-duplicate_class_parameters-check'
       - gem: 'puppet-lint-explicit_hiera_class_param_lookup-check'
       - gem: 'puppet-lint-legacy_facts-check'
       - gem: 'puppet-lint-trailing_newline-check'
       - gem: 'puppet-lint-variable_contains_upcase'
       - gem: 'puppet-lint-absolute_template_path'
       - gem: 'puppet-lint-strict_indent-check'
       - gem: 'puppet-lint-package_ensure-check'
       - gem: 'puppet-lint-concatenated_template_files-check'
       - gem: 'puppet-lint-no_symbolic_file_modes-check'
#      - gem: 'github_changelog_generator'
#        git: 'https://github.com/skywinder/github-changelog-generator'
#        ref: '20ee04ba1234e9e83eb2ffb5056e23d641c7a018'
#        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"
mock_with: ':rspec'
